"""Convert a .tflite model into CameraWebServer/led_model.h.

Emits the model bytes as a C array plus the input/output quantization
parameters and geometry the firmware needs, so train/inference never drift.

Usage:
    python convert_to_header.py model.tflite ../CameraWebServer/led_model.h
"""
import sys
import os
import tensorflow as tf

from model import INPUT_W, INPUT_H, INPUT_CH, NUM_CLASSES


def write_header(tflite_path, header_path):
    with open(tflite_path, "rb") as f:
        data = f.read()

    # Read quantization params straight from the model.
    interp = tf.lite.Interpreter(model_content=data)
    interp.allocate_tensors()
    inp = interp.get_input_details()[0]
    out = interp.get_output_details()[0]
    in_scale, in_zp = inp["quantization"]
    out_scale, out_zp = out["quantization"]

    lines = []
    lines.append("// Auto-generated by ml/convert_to_header.py — do not edit by hand.")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define LED_MODEL_INPUT_W {INPUT_W}")
    lines.append(f"#define LED_MODEL_INPUT_H {INPUT_H}")
    lines.append(f"#define LED_MODEL_INPUT_CH {INPUT_CH}")
    lines.append(f"#define LED_MODEL_NUM_CLASSES {NUM_CLASSES}")
    lines.append(f"#define LED_MODEL_INPUT_SCALE {in_scale:.10g}f")
    lines.append(f"#define LED_MODEL_INPUT_ZERO_POINT {int(in_zp)}")
    lines.append(f"#define LED_MODEL_OUTPUT_SCALE {out_scale:.10g}f")
    lines.append(f"#define LED_MODEL_OUTPUT_ZERO_POINT {int(out_zp)}")
    lines.append("")
    lines.append(f"const unsigned int g_led_model_len = {len(data)};")
    lines.append("alignas(8) const unsigned char g_led_model[] = {")
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 12])
        lines.append(f"  {chunk},")
    lines.append("};")
    lines.append("")

    with open(header_path, "w") as f:
        f.write("\n".join(lines))

    print(f"wrote {header_path} ({len(data)} model bytes)")
    print(f"  input  scale={in_scale:.6g} zero_point={int(in_zp)}")
    print(f"  output scale={out_scale:.6g} zero_point={int(out_zp)}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    write_header(sys.argv[1], sys.argv[2])
